Settings:
  Application:
    Host: 0.0.0.0
    Mode: dev
    Name: AppSidecar
    Port: 8000
  Database:
    Default:
      ConnMaxIdleTime: 0
      ConnMaxLifeTime: 0
      Driver: sqlite3
      MaxIdleConns: 0
      MaxOpenConns: 0
      Source: ./sqlite.db
    Standby:
      ConnMaxIdleTime: 0
      ConnMaxLifeTime: 0
      Driver: mysql
      MaxIdleConns: 0
      MaxOpenConns: 0
      Source: root:123456@tcp(127.0.0.1:3306)/test?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
  Jwt:
    Secret: App-Sidecar
    Timeout: 3600
  Logger:
    Cap: 1024000
    Level: info
    Location: false
    FileName: default
    FileSuffix: log
    Path: ./logs
    Enabled: true
  Queue:
    Memory:
      PoolSize: 100
  Redis:
    db: 0
    host: 127.0.0.1
    password: 123456
    port: 6379
  Ssl:
    Domain: localhost:8000
    Enable: false
    Key: ./temp/domain.key
    Pem: ./temp/domain.crt
