Settings:
  Application:
    Mode: dev
    Name: Go-Example
  Web:
    Host: 0.0.0.0
    Port: 8080
    Https: false
    Root: ./static/www/
    Domain: localhost
    CertFile: ./config/server.pem
    KeyFile: ./config/server.key
  Database:
    Default:
      Driver: sqlite3
      Source: ./sqlite.db
    Standby:
      Driver: mysql
      Source: root:123456@tcp(172.17.0.1:3306)/test?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
  Jwt:
    Secret: Go-Example
    Timeout: 3600
  Logger:
    Cap: 1024000
    Level: info
    Location: false
    FileName: default
    FileSuffix: log
    Path: ./logs
    Enabled: true
  Redis:
    db: 0
    host: 127.0.0.1
    password: 123456
    port: 6379